# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
  # The Node.js orb contains a set of prepackaged CircleCI configuration you can utilize
  # Orbs reduce the amount of configuration required for common tasks.
  # See the orb documentation here: https://circleci.com/developer/orbs/orb/circleci/node
  node: circleci/node@4.1
  # The CI Tools orb contains Kanopi related configurations.
  ci-tools: kanopi/ci-tools@1.7.1

jobs:
  build:
    docker:
      - image: cimg/node:14.15.0

    steps:
      - add_ssh_keys:
          fingerprints:
          - 4f:68:7b:a9:6c:6f:3a:3d:1b:24:d3:7e:30:f3:75:92
      - checkout
      - node/install-packages:
          pkg-manager: yarn

workflows:
  build:
    jobs:
      - build
